# 应用服务 WEB 访问端口
server:
  port: 8080

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/onlineauction?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root

# MyBatis Plus 配置
mybatis-plus:
  mapper-locations: classpath*:com/auction/onlineauction/OnlineAuction/mapper/xml/*.xml
  type-aliases-package: com.auction.onlineauction.OnlineAuction.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
